
import { StyleConfig, PainterStyle } from '../types';

export const STYLE_CONFIGS: Record<PainterStyle, StyleConfig> = {
  Default: {
    name: 'Default',
    bg: 'bg-slate-50',
    card: 'bg-white',
    text: 'text-slate-900',
    accent: 'bg-blue-600',
    border: 'border-slate-200',
    fontSans: 'font-sans',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-xl',
    shadow: 'shadow-sm',
  },
  VanGogh: {
    name: 'VanGogh',
    bg: 'bg-[#0F2027]',
    card: 'bg-[#203A43]/80 backdrop-blur-md',
    text: 'text-[#FAD961]',
    accent: 'bg-[#FAD961]',
    border: 'border-[#FAD961]/30',
    fontSans: 'font-serif',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-[2rem]',
    shadow: 'shadow-[0_0_20px_rgba(250,217,97,0.2)]',
  },
  Picasso: {
    name: 'Picasso',
    bg: 'bg-[#E6D5B8]',
    card: 'bg-[#F0A500]',
    text: 'text-[#1B1A17]',
    accent: 'bg-[#CF7500]',
    border: 'border-[#1B1A17] border-2',
    fontSans: 'font-sans font-bold',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-none',
    shadow: 'shadow-[10px_10px_0px_0px_rgba(27,26,23,1)]',
  },
  Mondrian: {
    name: 'Mondrian',
    bg: 'bg-white',
    card: 'bg-white',
    text: 'text-black',
    accent: 'bg-[#E70000]',
    border: 'border-black border-[4px]',
    fontSans: 'font-sans font-black uppercase tracking-tighter',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-none',
    shadow: 'shadow-none',
    grid: true,
  },
  Dali: {
    name: 'Dali',
    bg: 'bg-[#D4A373]',
    card: 'bg-[#FAEDCD]/90',
    text: 'text-[#432818]',
    accent: 'bg-[#99582A]',
    border: 'border-[#432818]/20',
    fontSans: 'font-serif italic',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-[30%_70%_70%_30%_/_30%_30%_70%_70%]',
    shadow: 'shadow-2xl',
  },
  Warhol: {
    name: 'Warhol',
    bg: 'bg-[#FF00FF]',
    card: 'bg-[#00FFFF]',
    text: 'text-black',
    accent: 'bg-[#FFFF00]',
    border: 'border-black border-4',
    fontSans: 'font-sans font-black italic',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-none',
    shadow: 'shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]',
  },
  Monet: {
    name: 'Monet',
    bg: 'bg-[#E0F2F1]',
    card: 'bg-white/60 backdrop-blur-xl',
    text: 'text-[#2E4F4F]',
    accent: 'bg-[#829460]',
    border: 'border-white/40',
    fontSans: 'font-serif',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-full',
    shadow: 'shadow-inner',
  },
  Basquiat: {
    name: 'Basquiat',
    bg: 'bg-[#121212]',
    card: 'bg-[#121212]',
    text: 'text-white',
    accent: 'bg-[#FFD700]',
    border: 'border-white border-dashed border-2',
    fontSans: 'font-mono uppercase',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-none',
    shadow: 'shadow-none',
  },
  Cyberpunk: {
    name: 'Cyberpunk',
    bg: 'bg-[#03001C]',
    card: 'bg-[#301E67]/40 backdrop-blur-md',
    text: 'text-[#B6EADA]',
    accent: 'bg-[#5B8FB9]',
    border: 'border-[#5B8FB9] border-l-4',
    fontSans: 'font-mono',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-none',
    shadow: 'shadow-[0_0_15px_rgba(91,143,185,0.5)]',
  },
  Bauhaus: {
    name: 'Bauhaus',
    bg: 'bg-[#F2F2F2]',
    card: 'bg-white',
    text: 'text-[#2D2D2D]',
    accent: 'bg-[#0055FF]',
    border: 'border-[#2D2D2D] border-2',
    fontSans: 'font-sans font-medium',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-none',
    shadow: 'shadow-none',
  },
  Rembrandt: {
    name: 'Rembrandt',
    bg: 'bg-[#1A120B]',
    card: 'bg-[#3C2A21]',
    text: 'text-[#D5CEA3]',
    accent: 'bg-[#E5E5CB]',
    border: 'border-[#D5CEA3]/10',
    fontSans: 'font-serif',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-md',
    shadow: 'shadow-[0_10px_30px_rgba(0,0,0,0.8)]',
  },
  Kandinsky: {
    name: 'Kandinsky',
    bg: 'bg-[#F9F7F7]',
    card: 'bg-[#3F72AF]',
    text: 'text-white',
    accent: 'bg-[#112D4E]',
    border: 'border-none',
    fontSans: 'font-sans font-light',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-[50%_20%_80%_10%]',
    shadow: 'shadow-lg',
  },
  Hokusai: {
    name: 'Hokusai',
    bg: 'bg-[#F8F1F1]',
    card: 'bg-[#116A7B]',
    text: 'text-white',
    accent: 'bg-[#C2D9FF]',
    border: 'border-[#C2D9FF]/20',
    fontSans: 'font-serif',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-tr-[5rem] rounded-bl-[5rem]',
    shadow: 'shadow-md',
  },
  Pollock: {
    name: 'Pollock',
    bg: 'bg-white',
    card: 'bg-white/10 backdrop-invert',
    text: 'text-black',
    accent: 'bg-black',
    border: 'border-black border-8',
    fontSans: 'font-mono font-black',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-none',
    shadow: 'shadow-none',
  },
  Matisse: {
    name: 'Matisse',
    bg: 'bg-[#FFB84C]',
    card: 'bg-[#F266AB]',
    text: 'text-white',
    accent: 'bg-[#A459D1]',
    border: 'border-none',
    fontSans: 'font-sans font-bold',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-[60%_40%_30%_70%_/_60%_30%_70%_40%]',
    shadow: 'shadow-xl',
  },
  Vermeer: {
    name: 'Vermeer',
    bg: 'bg-[#F2EAD3]',
    card: 'bg-white',
    text: 'text-[#3F2305]',
    accent: 'bg-[#DFD7BF]',
    border: 'border-[#3F2305]/10',
    fontSans: 'font-serif',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-sm',
    shadow: 'shadow-sm',
  },
  Degas: {
    name: 'Degas',
    bg: 'bg-[#F7EFE5]',
    card: 'bg-[#E2BFB3]',
    text: 'text-[#674188]',
    accent: 'bg-[#C8A1E0]',
    border: 'border-none',
    fontSans: 'font-serif italic',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-full',
    shadow: 'shadow-none',
  },
  Klimt: {
    name: 'Klimt',
    bg: 'bg-[#C07F00]',
    card: 'bg-[#FFD95A]',
    text: 'text-[#4C3D3D]',
    accent: 'bg-[#FFF7D4]',
    border: 'border-[#4C3D3D] border-double border-4',
    fontSans: 'font-serif font-black',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-none',
    shadow: 'shadow-[0_0_30px_rgba(192,127,0,0.5)]',
  },
  Kahlo: {
    name: 'Kahlo',
    bg: 'bg-[#0081C9]',
    card: 'bg-[#5BC0F8]',
    text: 'text-[#FFC93C]',
    accent: 'bg-[#86E5FF]',
    border: 'border-[#FFC93C] border-4',
    fontSans: 'font-serif font-bold',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-3xl',
    shadow: 'shadow-2xl',
  },
  Banksy: {
    name: 'Banksy',
    bg: 'bg-[#333333]',
    card: 'bg-[#333333]',
    text: 'text-white',
    accent: 'bg-[#FF0000]',
    border: 'border-white border-2 border-opacity-50',
    fontSans: 'font-mono uppercase italic',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-none',
    shadow: 'shadow-none',
  },
  Brutalist: {
    name: 'Brutalist',
    bg: 'bg-[#CCCCCC]',
    card: 'bg-white',
    text: 'text-black',
    accent: 'bg-[#0000FF]',
    border: 'border-black border-[3px]',
    fontSans: 'font-sans font-black uppercase tracking-widest',
    fontSerif: 'font-serif',
    fontMono: 'font-mono',
    radius: 'rounded-none',
    shadow: 'shadow-[12px_12px_0px_0px_rgba(0,0,0,1)]',
  },
};
